import React from 'react';
import { CardData } from '../services/gemini';

interface CardPreviewProps {
  card: CardData;
  index: number;
  total: number;
  id: string;
}

export const CardPreview: React.FC<CardPreviewProps> = ({ card, index, total, id }) => {
  return (
    <div
      id={id}
      className="w-[1080px] h-[1440px] bg-[#F8F9FA] flex flex-col font-sans text-[#333] shrink-0 box-border"
    >
      {/* Header */}
      <div className="flex items-center justify-between px-16 py-12 border-b-2 border-gray-200 bg-white shrink-0">
        <div className="flex items-center gap-6">
          <div className="w-16 h-16 bg-gradient-to-br from-red-500 to-orange-500 rounded-full flex items-center justify-center text-white font-bold text-2xl shadow-md">
            AI
          </div>
          <span className="text-4xl font-bold tracking-wider text-gray-800">Tech Insights</span>
        </div>
        <span className="text-4xl text-gray-400 font-medium tracking-widest">{index}/{total}</span>
      </div>

      {/* Body */}
      <div className="flex-1 p-16 flex flex-col gap-10 overflow-hidden">
        {card.layout === 'image_top' && card.imageUrl && (
          <div className="w-full h-[420px] rounded-3xl overflow-hidden shadow-lg border border-gray-100 shrink-0">
            <img src={card.imageUrl} alt="Illustration" className="w-full h-full object-cover" referrerPolicy="no-referrer" />
          </div>
        )}

        <h1 className="text-[64px] font-black leading-[1.2] tracking-tight text-gray-900 shrink-0">
          {card.title}
        </h1>

        <div
          className="text-[40px] leading-[1.6] text-gray-700 whitespace-pre-wrap font-medium flex-1 overflow-hidden"
          dangerouslySetInnerHTML={{ __html: card.content.replace(/<b>/g, '<b class="text-black font-black">').replace(/<u>/g, '<u class="text-red-600 font-black decoration-red-500 decoration-[6px] underline-offset-[8px]">') }}
        />

        {card.layout === 'image_bottom' && card.imageUrl && (
          <div className="w-full h-[420px] rounded-3xl overflow-hidden shadow-lg border border-gray-100 mt-auto shrink-0">
            <img src={card.imageUrl} alt="Illustration" className="w-full h-full object-cover" referrerPolicy="no-referrer" />
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="px-16 py-12 flex justify-between items-center bg-white border-t-2 border-gray-200 shrink-0">
        <div className="text-3xl text-gray-400 font-medium tracking-wide">@Generated by巴顿带你看AI大事</div>
      </div>
    </div>
  );
};
